routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	
	Route::resource('post', 'PostMemo');
    Route::match(['get','post'], 'post-memo', 'PostMemo@post')->name('post.post');
    Route::get('post-get-notif', 'PostMemo@getNotifCount')->name('post.get-count');
});

app/Memo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Memo extends Model
{
    protected $table = 'memos';

    public static function postMemo(Request $request)
    {
        $title = $request->get('posttitle');
        $date = $request->get('postexp');
        $content = $request->get('postcontent');
        $url = $request->get('posturl');
        $blob = $request->get('blobimage');

        $memo = new Memo;

        $memo->title = $title;
        $memo->content = $content;
        $memo->imgpath = $url;
        $memo->blob = $blob;
        $memo->expiration = $date;
        
        // dd($memo);
        $memo->save();

        return $memo;
    }
}

resources/views/layouts/page_templates/memo/index.blade.php
@extends('layouts.app', ['activePage' => 'postMemo', 'titlePage' => 'Post Meno'])

@section('content')
	<div class="content">
		<div class="container-fluid">
			<form class="form" method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
				@csrf
				<div class="row">
					<div class="col-5">
						<div class="bmd-form-group mt-3">
							<div class="input-group">
								<div class="input-group-prepend">
									<span class="input-group-text">
										<i class="material-icons">attach_file</i>
									</span>
								</div>
								<input type="file" name="fileUpload" id="fileUpload" class="form-control" placeholder="Upload File" value="" required>
							</div>
						</div>
					</div>
					<div class="col-2">
						<button type="submit" class="btn btn-danger">Scan Image</button>
					</div>
				</div>
			</form>
			<form class="form" method="POST" action="{{ route('post.post') }}" enctype="multipart/form-data">
				@csrf
				<br><br>
				<div class="align-items-center" style="width:50%;">
					<div class="bmd-form-group mt-3">
						<div class="input-group">
							<div class="input-group-prepend"><span class="input-group-text">Post Title</span></div>
							<input type="text" name="posttitle" id="posttitle" class="form-control" placeholder="Title">
						</div>
					</div>
					
					<div class="bmd-form-group mt-3">
						<div class="input-group">
							<div class="input-group-prepend"><span class="input-group-text">Expiration</span></div>
							<input type="date" name="postexp" id="postexp" class="form-control" placeholder="Title" >
						</div>
					</div>

					<div class="bmd-form-group mt-3">
						<div class="input-group">
							<div class="input-group-prepend"><span class="input-group-text">Content</span></div>
							<textarea rows="10" cols="100" class="form-control">
								{{ (isset($message) && $message != "") ? $message : ""  }}
							</textarea>
							<input type="text" name="postcontent" id="postcontent" hidden value="{{ (isset($message) && $message != "") ? $message : ""  }}">
						</div>
					</div>
					
					<div class="bmd-form-group mt-3">
						<br><br>
						<div class="input-group">
							<input type="text" name="posturl" id="posturl" value="{{ (isset($path) && $path != "") ? $path : ""  }}" hidden>
							<input type="text" name="blobimage" id="blobimage" value="{{ (isset($blobimage) && $blobimage != "") ? $blobimage : ""  }}" hidden>
							<img class="img-fluid" src="{{ (isset($path) && $path != "") ? $path : "" }}" alt="No Content">
						</div>
					</div>
					
					<br><br>
					<button type="submit" class="btn btn-danger" style="width: 100%">Post Memo</button>
				</div>
			</form>
		</div>
	</div>
@endsection

resources/views/layouts/page_templates/memo/view.blade.php
@extends('layouts.app', ['activePage' => 'postMemo', 'titlePage' => 'Post Meno'])

@section('content')
	<div class="content">
		<div class="container-fluid">
            <div class="align-items-center" style="width:50%;">
                <div class="bmd-form-group mt-3">
                    <div class="input-group">
                        <div class="input-group-prepend"><span class="input-group-text">Post Title</span></div>
                        <input type="text" name="posttitle" id="posttitle" class="form-control" placeholder="Title" value="{{$title}}">
                    </div>
                </div>
                <div class="bmd-form-group mt-3">
                    <div class="input-group">
                        <div class="input-group-prepend"><span class="input-group-text">Expiration Date</span></div>
                        <input type="text" name="posttitle" id="posttitle" class="form-control" placeholder="Title" value="{{$expiration}}">
                    </div>
                </div>

                <br><br>
                <div class="bmd-form-group mt-12">
                    <div class="input-group">
                        <div class="input-group-prepend"><span class="input-group-text">Content</span></div>
                        <textarea rows="15" cols="200" class="form-control">
                            {{ (isset($content) && $content != "") ? $content : ""  }}
                        </textarea>
                    </div>
                </div>
                
                <div class="bmd-form-group mt-3">
                    <br><br>
                    <div class="input-group">\
                        <img class="img-fluid" src="{{ (isset($blob) && $blob != "") ? $blob : "" }}" alt="No Content">
                    </div>
                </div>
                
                <br><br>
                <button type="submit" class="btn btn-danger" style="width: 100%">Receive Memo</button>
            </div>
		</div>
	</div>
@endsection